Typo3 12 compatibility
jweiland-net/replacer pull request #23
Opened 2023-09-07 06:04 UTC by hojalatheef

2023-09-07 07:41 UTC, sfroemkenjw requested changes

2023-09-07 07:41 UTC, sfroemkenjw commented on .github/workflows/ci.yml
> +  schedule:
Executing the Github Actions every day at 4:27? Why?
I would prefer removing that line

2023-09-07 07:41 UTC, sfroemkenjw commented on .github/workflows/testscorev11.yml
> +  schedule:
Remove scheduled Github Action

2023-09-07 07:41 UTC, sfroemkenjw commented on .github/workflows/ci.yml
> -# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
Please remove that file completely. You already have: testscorev12.yml

2023-09-07 07:41 UTC, sfroemkenjw commented on .github/workflows/testscorev12.yml
> +  schedule:
Remove

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/FunctionalTests.xml
> +        <const name="TYPO3_MODE" value="BE" />
There is no TYPO3_MODE in TYPO3 anymore. And it is deprecated in TYPO3 11, too. Sure, we still need that?

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/Scripts/runTests.sh
> +jweiland replacer test runner. Execute unit test suite and some other details.
Very good. You have replaced the extkey here, too.

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/UnitTests.xml
> +        <const name="TYPO3_MODE" value="BE" />
Same as above. Remove TYPO3_MODE or find a replacement

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/UnitTestsBootstrap.php
> +    $requestType = \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE | \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_CLI;
As you see the Testing Framework can resolve the TYPO3_MODE itself. No need to define it in the XML files.

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/php-cs-fixer/config.php
>          'array_syntax' => ['syntax' => 'short'],
I just see that there is no header comment check in Avalex. That's wrong. Can you please keep the header comment check here?

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/php-cs-fixer/config.php
> +        'modernize_strpos' => false,
Just you your information. That should be true in future. We have to keep it false as long as we still support PHP 7.4.

2023-09-07 07:41 UTC, sfroemkenjw commented on Build/testing-docker/docker-compose.yml
> +          XDEBUG_MODE=\"debug,develop\" XDEBUG_TRIGGER=\"foo\" XDEBUG_CONFIG=\"client_host=host.docker.internal\" $${COMMAND};
Just for your information: In original files of Christian Kuhn (lolli) extensions these xdebug rows are separated in multiple lines. But that will break on Mac with Docker Compose 2. So these lines have to be in one single long row like I have done here.

2023-09-07 07:41 UTC, sfroemkenjw commented on Classes/Frontend/EventListener/CacheableContentGeneratedEventListener.php
> +    public function getReplaceHelper() : ReplacerHelper
Perfect, but please remove the space between method and `:`

2023-09-07 07:41 UTC, sfroemkenjw commented on Configuration/Services.yaml
> +  # general settings
Remove that comment. We DEVs know what these 3 rows mean ;-)

2023-09-07 07:41 UTC, sfroemkenjw commented on Documentation/Configuration/Index.rst
> +..  include:: /Includes.rst.txt
Perfect. You have updated the include path, too. Nice ;-)

2023-09-07 07:41 UTC, sfroemkenjw commented on Documentation/Configuration/Index.rst
> +..  _configuration:
4 spaces indents. Perfect.

2023-09-07 07:41 UTC, sfroemkenjw commented on Documentation/Includes.rst.txt
> +   https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html#includes-rst-txt
Add a space. We need 4 space indent

2023-09-07 07:41 UTC, sfroemkenjw commented on Tests/Functional/Fixtures/pages.csv
> +"pages",,,,,,,,,,,,,,
NIce...you have converted the XML to the new CSV default.

2023-09-07 07:41 UTC, sfroemkenjw commented on Tests/Functional/Hooks/TypoScriptFrontendControllerTest.php
> +        'jweiland/replacer'
Nice. You have used the new composer package name here.

2023-09-07 07:41 UTC, sfroemkenjw commented on Tests/Functional/Middleware/ReplaceContentTest.php
> +     * @var array
Please remove, as it is already type-hinted in variable definition below.

2023-09-07 07:41 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> -/*
After repairing the header comment check in testing files above this will fail. Please re-add the header comment.

2023-09-07 07:41 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +        $value = $configProperty->getValue($frontendController);
IMO `$value` is not used anywhere

2023-09-07 07:41 UTC, sfroemkenjw commented on composer.json
> +		"php": ">=7.4",
We don't add any PHP dependencies. That's the job of TYPO3.

2023-09-07 07:41 UTC, sfroemkenjw commented on composer.json
>  		"typo3-ter/scriptmerger": "<7.0.0",
IMO the vendor `typo3-ter` comes from the deprecated and removed composer.typo3.org repository. Please update this package to accordingly: https://packagist.org/packages/sgalinski/scriptmerger

2023-09-07 07:41 UTC, sfroemkenjw commented on ext_localconf.php
> +<?php defined('TYPO3') or die();
Please do not add any further PHP code in first line of PHP files:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/CodingGuidelines/CglPhp/PhpFileFormatting/GeneralRequirementsForPhpFiles.html#php-tags

2023-09-07 07:41 UTC, sfroemkenjw commented on ext_localconf.php
> +    // To check version
Just comment, if it is an added value. That one here is obviously. So please remove.

2023-09-07 07:41 UTC, sfroemkenjw commented on ext_localconf.php
> +});
Don't see it here. Is there an empty line at end of file?

2023-09-07 07:49 UTC, hojalatheef commented on .github/workflows/ci.yml
> -# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
@sfroemkenjw You're 100% correct its reduntant. I removed the CI Job from the list

2023-09-07 08:06 UTC, hojalatheef commented on Build/FunctionalTests.xml
> +        <const name="TYPO3_MODE" value="BE" />
Yeah we changed the 11 min. dependeny to the higher one. So now we can remove it here too.

2023-09-07 08:17 UTC, hojalatheef commented on Build/php-cs-fixer/config.php
>          'array_syntax' => ['syntax' => 'short'],
Yes I got the config. from Avalex. I put the header comment check back now.

2023-09-07 08:31 UTC, hojalatheef commented on Classes/Frontend/EventListener/CacheableContentGeneratedEventListener.php
> +    public function getReplaceHelper() : ReplacerHelper
Already Done! Phew! I forget to add the CGL task in github. I executed and it notified about this space in that test 👍

2023-09-07 08:41 UTC, hojalatheef commented on Documentation/Includes.rst.txt
> +   https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html#includes-rst-txt
WoW you noted that one space 😱

2023-09-07 08:57 UTC, hojalatheef commented on ext_localconf.php
> +});
yeah sure. even if I forget to put one ps will do it

2023-09-07 09:33 UTC, sfroemkenjw requested changes

2023-09-07 09:33 UTC, sfroemkenjw commented on .github/workflows/testscorev11.yml
> +    name: PHP Unit and Functional Tests for TYPO3 Version 11LTS
Space between 11 and LTS

2023-09-07 09:33 UTC, sfroemkenjw commented on .github/workflows/testscorev12.yml
> +name: Test replacer for TYPO3 12LTS
Space between 12 and LTS

2023-09-07 09:33 UTC, sfroemkenjw commented on .github/workflows/testscorev12.yml
> +    name: PHP Unit and Functional Tests for TYPO3 Version 12LTS
Space between 12 and LTS

2023-09-07 09:33 UTC, sfroemkenjw commented on Classes/Helper/ReplacerHelper.php
> +use function count;
Do we need that? I would prefer to remove that.

2023-09-07 09:33 UTC, sfroemkenjw commented on Configuration/Services.yaml
> +  # This event listener is implemented for replacing the Hook implementation which is removed in TYPO3 12LTS
Space between 12 and LTS

2023-09-07 09:33 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +        $configProperty = new ReflectionProperty($frontendController, 'config');
Please keep `\` for classes on PHP root namespace. That way it's much easier to see, if you have build up your own  ReflectionProperty or if you're using the PHP class without scrolling up to top of class.

2023-09-07 09:33 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +use ReflectionException;
Remove. See my comment below.

2023-09-07 09:33 UTC, sfroemkenjw commented on composer.json
>  		"sgalinski/scriptmerger": "<7.0.0"
OK for me. But I though you wanted to remove that completely?

2023-09-07 09:36 UTC, hojalatheef commented on composer.json
>  		"sgalinski/scriptmerger": "<7.0.0"
@froemken Yeah I thought we can keep it because in case some one have issues with this extension's new version. It gives a clue!. What do you think?

2023-09-07 10:18 UTC, sfroemkenjw requested changes

2023-09-07 10:18 UTC, sfroemkenjw commented on Documentation/Links.rst
> +	https://docs.typo3.org/p/jweiland/replacer/main/en-us/
Please use spaces here. No tabs.

2023-09-07 11:54 UTC, sfroemkenjw commented on composer.json
>  		"sgalinski/scriptmerger": "<7.0.0"
As I have written: "OK for me". You have a meaningful explanation for that, so keep it ;-)

2023-09-08 07:15 UTC, sfroemkenjw requested changes

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/ChangeLog/Index.rst
> +================================================
All these lines have to match the exact amount of chars of the above header.

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/ChangeLog/Index.rst
> +*   Add support for TYPO3 v11 LTS
Please add an empty line after each header
See: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html#headlines

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/Configuration/TypoScript/Index.rst
> +**Basic example** ::
There is a TypoScript formatter in Sphinx.

Please use that:
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html#code-block-directive

TypoScript role:
https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual/blob/main/Documentation/Includes.rst.txt?plain=1#L20

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/Configuration/TypoScript/Index.rst
> +**Basic example** ::
And, as always: The first indents are always 4 spaces. The second indents are TypoScript specific with 2 spaces.

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
> +Take a look into the :ref:`stdWrap <t3tsref:stdwrap>` documentation for more information.
Very good. You found the TYPO3 references.

2023-09-08 07:15 UTC, sfroemkenjw commented on Documentation/Introduction/Index.rst
> +The TYPO3 Replacer Extension provides a flexible solution for replacing string patterns and regular expressions on your pages. This can be particularly useful for tasks such as replacing URLs for Con
In .editorconfig of TYPO3 we have a max line of 80:
https://github.com/TYPO3/typo3/blob/main/.editorconfig#L26

Please adopt all text parts to max line 80.

Except: code-snippets

2023-09-08 07:15 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +final class ReplacerHelperTest extends UnitTestCase
Good point. I have never done that. But as TYPO3 declares their tests also final, this is super OK.

2023-09-08 07:15 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +        $this->configurationManager = $this->getMockBuilder(ConfigurationManager::class)->disableOriginalConstructor()->getMock();
Just use "createMock()". It's much shorter and it also disables the constructor.

2023-09-08 07:15 UTC, sfroemkenjw commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +        parent::setUp();
Please move that to top of method. Always.

2023-09-08 07:35 UTC, hojalatheef commented on Tests/Unit/Helper/ReplacerHelperTest.php
> +        $this->configurationManager = $this->getMockBuilder(ConfigurationManager::class)->disableOriginalConstructor()->getMock();
Done

2023-09-08 09:48 UTC, sfroemkenjw requested changes

2023-09-08 09:48 UTC, sfroemkenjw commented on Classes/Helper/ReplacerHelper.php
> +    protected function processContent($content, $configKey): ?string
Please add strict typing for $content and $configKey. In that case, we can be sure that $content is string and we can also return just string instead of ?string. And there is no need to check against $configKey to be array anymore.

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Configuration/TypoScript/Index.rst
>  Now, when visitors view your website, they will see "banana" instead of "apple" wherever it was originally used.
New line after each header

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Configuration/TypoScript/Index.rst
> +Using a regular expression (regex) as a search pattern in the Replacer Extension provides a powerful way to perform
New line after each header

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Configuration/TypoScript/Index.rst
> +Now, when visitors view your website, they will see the modified content with the replaced patterns based on the regular
New line after each header

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
>  **Replace content within a paragraph** ::
Remove these "::" as they will initiate following text lines as code-block

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
>  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
This header is not TYPO3 convention. Please adopt heading order from here: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html#headlines

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
>  **CDN example:** ::
Please remove trailing "::" to prevent creating a code block

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
>  **Use page title as replacement** ::
Remove "::" to prevent creating a code block afterwards

2023-09-08 09:48 UTC, sfroemkenjw commented on Documentation/Example/Index.rst
>  **Use page modification date as replacement** ::
Remove "::"

2023-09-08 11:39 UTC, merged