[ADD] replace @ composer
jweiland-net/replacer pull request #33
Opened 2023-09-15 12:29 UTC by xerc

2023-09-21 14:08 UTC, sfroemkenjw requested changes

2023-09-21 14:08 UTC, sfroemkenjw commented on composer.json
> +		"typo3-ter/ja-replacer": "*",
The `typo3-ter` vendor was part of the composer.typo3.org repository. This repo is out-dated since years. Please remove the both typo3-ter entries and I will merge your patch.

Stefan

2023-09-21 17:12 UTC, xerc commented
as long TER is running their GIT repo it is not wise to not have these specified

2023-09-22 08:06 UTC, sfroemkenjw approved these changes

2023-09-22 08:06 UTC, merged

2023-09-22 08:10 UTC, sfroemkenjw commented
We already have removed that old repo from all of our projects and I don't know when TYPO3 will shutdown that repo. I'm really not happy to support that, but as long as there are community people out there, still using or not knowing this deprecation I will merge your patch now.